import os
import zlib
import struct
from Crypto.Cipher import AES
from Crypto.Random import get_random_bytes
from argon2.low_level import hash_secret_raw, Type

# --- Key Derivation ---
def derive_key(password: str, salt: bytes) -> bytes:
    """Derive a 256-bit key using Argon2id."""
    return hash_secret_raw(
        secret=password.encode('utf-8'),
        salt=salt,
        time_cost=3,
        memory_cost=65536,
        parallelism=4,
        hash_len=32,
        type=Type.ID
    )

# --- Encryption / Decryption ---
def encrypt_payload(data: bytes, password: str) -> bytes:
    """Compress and encrypt payload using AES-256-GCM."""
    compressed_data = zlib.compress(data, level=9)
    salt = get_random_bytes(16)
    key = derive_key(password, salt)
    
    cipher = AES.new(key, AES.MODE_GCM)
    ciphertext, tag = cipher.encrypt_and_digest(compressed_data)
    
    # Return salt + nonce + tag + ciphertext
    return salt + cipher.nonce + tag + ciphertext

def decrypt_payload(encrypted_data: bytes, password: str) -> bytes:
    """Decrypt and decompress payload using AES-256-GCM."""
    if len(encrypted_data) < 16 + 16 + 16:
        raise ValueError("Invalid encrypted data length")
        
    salt = encrypted_data[:16]
    nonce = encrypted_data[16:32]
    tag = encrypted_data[32:48]
    ciphertext = encrypted_data[48:]
    
    key = derive_key(password, salt)
    cipher = AES.new(key, AES.MODE_GCM, nonce=nonce)
    
    try:
        compressed_data = cipher.decrypt_and_verify(ciphertext, tag)
        return zlib.decompress(compressed_data)
    except ValueError:
        raise ValueError("Decryption failed: Incorrect password or corrupted data")
    except zlib.error:
         raise ValueError("Decompression failed: Corrupted data")


# --- Payload Structure Framing ---
# We use a custom structure to store the data
# Format: [Magic Bytes] [Version] [Primary Payload Length] [Primary Payload] [Has Decoy Flag] [Decoy Payload Length] [Decoy Payload]
# We'll keep it simpler. Let the embedder just store a raw byte stream. 
# The raw byte stream will be generated by `prepare_stego_payload`.

MAGIC_BYTES = b"AEGS"
VERSION = 1

def prepare_stego_payload(primary_data: bytes, primary_password: str, 
                          decoy_data: bytes = None, decoy_password: str = None) -> bytes:
    """
    Prepares the final byte stream to be embedded into the image.
    Supports plausible deniability via a decoy payload.
    """
    # 1. Encrypt primary data
    enc_primary = encrypt_payload(primary_data, primary_password)
    primary_len = len(enc_primary)
    
    # 2. Handle decoy if provided
    has_decoy = 1 if decoy_data and decoy_password else 0
    enc_decoy = b""
    decoy_len = 0
    
    if has_decoy:
        enc_decoy = encrypt_payload(decoy_data, decoy_password)
        decoy_len = len(enc_decoy)
        
    # 3. Pack everything together
    # [Magic: 4 bytes] [Version: 1 byte] [HasDecoy: 1 byte] [PrimaryLen: 4 bytes] [PrimaryData] [DecoyLen: 4 bytes] [DecoyData]
    
    header = struct.pack("<4sBB", MAGIC_BYTES, VERSION, has_decoy)
    primary_part = struct.pack("<I", primary_len) + enc_primary
    
    decoy_part = b""
    if has_decoy:
        decoy_part = struct.pack("<I", decoy_len) + enc_decoy
        
    return header + primary_part + decoy_part

def parse_stego_payload(payload: bytes, password: str) -> bytes:
    """
    Parses the extracted stego payload and attempts to decrypt it.
    It automatically tries to decrypt the primary payload, and if that fails, 
    it tries the decoy payload (if it exists).
    
    Raises ValueError on incorrect password.
    """
    if len(payload) < 6:
        raise ValueError("Payload too short to contain header")
        
    magic, version, has_decoy = struct.unpack("<4sBB", payload[:6])
    
    if magic != MAGIC_BYTES:
         raise ValueError("Invalid magic bytes")
         
    if version != VERSION:
         raise ValueError("Unsupported payload version")
         
    offset = 6
    if len(payload) < offset + 4:
        raise ValueError("Payload corrupted (missing primary length)")
        
    primary_len = struct.unpack("<I", payload[offset:offset+4])[0]
    offset += 4
    
    if len(payload) < offset + primary_len:
         raise ValueError("Payload corrupted (missing primary data)")
         
    enc_primary = payload[offset:offset+primary_len]
    offset += primary_len
    
    enc_decoy = b""
    if has_decoy:
        if len(payload) < offset + 4:
            raise ValueError("Payload corrupted (missing decoy length)")
        decoy_len = struct.unpack("<I", payload[offset:offset+4])[0]
        offset += 4
        if len(payload) < offset + decoy_len:
             raise ValueError("Payload corrupted (missing decoy data)")
        enc_decoy = payload[offset:offset+decoy_len]
        
    # Attempt decryption
    errors = []
    
    try:
        return decrypt_payload(enc_primary, password)
    except ValueError as e:
        errors.append(f"Primary: {e}")
        
    if has_decoy:
        try:
            return decrypt_payload(enc_decoy, password)
        except ValueError as e:
            errors.append(f"Decoy: {e}")
            
    raise ValueError(f"Decryption failed for all available payloads. Errors: {'; '.join(errors)}")
