import os
import re
import subprocess
import tempfile
from pathlib import Path

import typer

from eva.ui.formatter import print_error


def _fix_diff_headers(diff_text: str) -> str:
    """Fixes malformed hunk headers (e.g., bare '@@') generated by LLMs."""
    lines = diff_text.strip().splitlines()
    fixed_lines = []
    current_file = None
    target_content = []

    i = 0
    while i < len(lines):
        line = lines[i]
        if line.startswith(("--- ", "+++ ")):
            current_file = line[4:].strip()
            if current_file.startswith(("a/", "b/")):
                current_file = current_file[2:]

            fixed_lines.append(line)

            if line.startswith("+++ "):
                try:
                    with open(current_file, "r", encoding="utf-8") as f:
                        target_content = f.read().splitlines()
                except (OSError, UnicodeDecodeError):
                    target_content = []
        elif line.strip() == "@@":
            old_lines = []
            j = i + 1
            while j < len(lines) and not lines[j].startswith("@@") and not lines[j].startswith("---"):
                if lines[j].startswith("-") or lines[j].startswith(" "):
                    old_lines.append(lines[j][1:])
                j += 1

            start_idx = 0
            if old_lines and target_content:
                for k in range(len(target_content) - len(old_lines) + 1):
                    if target_content[k : k + len(old_lines)] == old_lines:
                        start_idx = k
                        break

            start_line = start_idx + 1
            fixed_lines.append(f"@@ -{start_line},1 +{start_line},1 @@")
        else:
            fixed_lines.append(line)
        i += 1

    return "\n".join(fixed_lines) + "\n"


def extract_unified_diff(model_output: str) -> str:
    text = model_output.strip()
    fenced = re.fullmatch(r"```(?:diff|patch)?\s*\n(?P<body>.*?)\n```", text, flags=re.DOTALL)
    if fenced:
        text = fenced.group("body").strip()

    if "\n--- " not in f"\n{text}" and "\ndiff --git " not in f"\n{text}":
        raise ValueError("model did not return a unified diff")

    cleaned_lines = []
    for line in text.splitlines():
        if line.startswith(("***", "Apply", "End of File")):
            break
        cleaned_lines.append(line)

    cleaned_text = "\n".join(cleaned_lines)
    return _fix_diff_headers(cleaned_text)


def apply_diff_python_fallback(diff_text: str) -> bool:
    """
    Parses a unified diff (even with bad hunk headers or extra trailing text)
    and applies it directly to files on disk using fuzzy line matching.
    Returns True if at least one file was modified, False otherwise.
    """
    lines = diff_text.splitlines()
    files_hunks = {}
    current_file = None
    current_hunk = None

    i = 0
    while i < len(lines):
        line = lines[i]
        if line.startswith(("--- ", "+++ ")):
            fname = line[4:].strip()
            if fname.startswith(("a/", "b/")):
                fname = fname[2:]
            current_file = fname
            if current_file not in files_hunks:
                files_hunks[current_file] = []
        elif line.startswith("@@"):
            if current_hunk is not None and current_file:
                files_hunks[current_file].append(current_hunk)
            current_hunk = []
        elif current_hunk is not None:
            if line.startswith(("***", "Apply", "End of File")):
                break
            if line.startswith(("-", "+", " ")) or line == "":
                current_hunk.append(line)
            else:
                current_hunk.append(" " + line)
        i += 1

    if current_hunk is not None and current_file:
        files_hunks[current_file].append(current_hunk)

    modified_any = False

    root_dir = Path.cwd().resolve()

    for filename, hunks in files_hunks.items():
        if not filename:
            continue
        try:
            p = Path(filename)
            target_path = p.resolve() if p.is_absolute() else (root_dir / filename).resolve()
        except (ValueError, OSError):
            continue

        if not target_path.is_file():
            continue

        try:
            with open(target_path, "r", encoding="utf-8") as f:
                file_content = f.read()
        except (OSError, UnicodeDecodeError):
            continue

        file_lines = file_content.splitlines()

        for hunk in hunks:
            old_slice = []
            new_slice = []
            for hline in hunk:
                if hline.startswith("-"):
                    old_slice.append(hline[1:])
                elif hline.startswith("+"):
                    new_slice.append(hline[1:])
                elif hline.startswith(" "):
                    old_slice.append(hline[1:])
                    new_slice.append(hline[1:])

            if not old_slice:
                continue

            match_idx = -1
            for k in range(len(file_lines) - len(old_slice) + 1):
                if [l.strip() for l in file_lines[k : k + len(old_slice)]] == [l.strip() for l in old_slice]:
                    match_idx = k
                    break

            if match_idx != -1:
                file_lines = file_lines[:match_idx] + new_slice + file_lines[match_idx + len(old_slice) :]

        updated_text = "\n".join(file_lines)
        if file_content.endswith("\n"):
            updated_text += "\n"

        if updated_text != file_content:
            with open(target_path, "w", encoding="utf-8") as f:
                f.write(updated_text)
            modified_any = True

    return modified_any


def apply_unified_diff(diff_text: str):
    with tempfile.NamedTemporaryFile("w", suffix=".patch", delete=False, encoding="utf-8") as tmp:
        tmp.write(diff_text)
        patch_path = tmp.name

    try:
        check = subprocess.run(
            ["git", "apply", "--unidiff-zero", "--recount", "--check", patch_path],
            capture_output=True,
            text=True,
            check=False,
        )
        if check.returncode == 0:
            applied = subprocess.run(
                ["git", "apply", "--unidiff-zero", "--recount", patch_path], capture_output=True, text=True, check=False
            )
            if applied.returncode == 0:
                return
    except FileNotFoundError:
        pass
    finally:
        try:
            os.unlink(patch_path)
        except OSError:
            pass

    # Fallback to Python-based fuzzy patch applier if git apply fails or is missing
    success = apply_diff_python_fallback(diff_text)
    if not success:
        print_error("Patch apply failed. Could not match diff hunks with target file.")
        raise typer.Exit(1)


def run_git(args: list[str]) -> subprocess.CompletedProcess[str]:
    try:
        return subprocess.run(["git", *args], capture_output=True, text=True, check=False)
    except FileNotFoundError:
        print_error("git is not installed on this system.")
        raise typer.Exit(1)
